package cat.grogg.empire

sealed class EmpirePost(
    open val name: String,
    open val lore: String? = null,
    open val stats: String? = null,
    open val ethics: String? = null,
    open val special: String? = null
) {
    fun toEmpire() = Empire(
        id = 0, // ID will be generated by the database
        name = name,
        lore = lore,
        stats = stats,
        ethics = ethics,
        special = special
    )
}

data class Empire(
    val id: Int,
    override val name: String,
    override val lore: String?,
    override val stats: String?,
    override val ethics: String?,
    override val special: String?
): EmpirePost(name, lore, stats, ethics, special)